version: '3'

services:
    squid:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: squid
      restart: always
      ports:
        - 3128:3128
      #volumes:
      #  - ./squid/cache:/var/spool/squid
      #  - ./squid/logs:/var/log/squid

    nginx:
      image: nginx:alpine
      container_name: nginx
      volumes:
        - ./proxy.pac:/usr/share/nginx/html/proxy.pac
      ports:
        - 8000:80
      depends_on:
        - squid
