services:
  squid:
    image: ubuntu/squid:latest
    container_name: squid
    restart: always
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./proxy.pac:/usr/share/nginx/html/proxy.pac
    ports:
      - "8000:80"
    depends_on:
      - squid

